In [ ]:
from safetensors.torch import load_file
import pandas as pd
import polars as pl
import torch
from tqdm import tqdm
import numpy as np

EXPERT_ID = 7
W_ID = 1
LAYER_ID = 16


if __name__ == "__main__":
    files = []
    for i in range(100):
        p = f"output_100/layer={LAYER_ID:02}/router.safetensors"
        files.append(p)


    row_ids = []
    titles = []
    scores = []


    for path in tqdm(files):
        tensors = []
        weights = load_file(path, device="mps")
        for k, v in weights.items():
            row_id, title = k.split(".", 1) # split left most ".":
            row_ids.append(row_id)
            titles.append(title)

            score = v[-1, EXPERT_ID]
            scores.append(score)
    
    scores_tensor = torch.tensor(scores)
    top_1000 = torch.topk(scores_tensor, 1000, dim=0, sorted=True)
    top_1000_indices_np = top_1000.indices.cpu().numpy()
    top_1000_scores_np = top_1000.values.cpu().numpy()

    titles_np = np.array(titles)
    top_1000_titles = titles_np[top_1000_indices_np]

    df = pd.DataFrame({
        "title": top_1000_titles,
        "score": top_1000_scores_np,
    })

    df.to_csv(f"router_statistics_layer{LAYER_ID}_expert{EXPERT_ID}_w{W_ID}.csv", index=False)

In [90]:
import pandas as pd

py_df = pd.read_csv('data/py_repos.csv', usecols=['rank', 'username/repo_name'])
all_safetensor_keys = set(f'{row["rank"]}.{row["username/repo_name"]}' for _, row in py_df.iterrows())
all_safetensor_keys

{'100.chubin/wttr.in',
 '11.josephmisiti/awesome-machine-learning',
 '12.public-apis/public-apis',
 '13.donnemartin/system-design-primer',
 '13.huggingface/transformers',
 '15.psf/requests',
 '16.521xueweihan/HelloGitHub',
 '18.scrapy/scrapy',
 '19.soimort/you-get',
 '20.minimaxir/big-list-of-naughty-strings',
 '21.ageitgey/face_recognition',
 '22.apache/superset',
 '23.TheAlgorithms/Python',
 '24.deepfakes/faceswap',
 '25.3b1b/manim',
 '25.jackfrued/Python-100-Days',
 '26.tiangolo/fastapi',
 '26.vinta/awesome-python',
 '27.ytdl-org/youtube-dl',
 '28.fighting41love/funNLP',
 '29.0voice/interview_internal_reference',
 '30.localstack/localstack',
 '31.isocpp/CppCoreGuidelines',
 '32.apachecn/AiLearning',
 '33.pandas-dev/pandas',
 '34.floodsung/Deep-Learning-Papers-Reading-Roadmap',
 '35.testerSunshine/12306',
 '36.faif/python-patterns',
 '37.google-research/bert',
 '38.getsentry/sentry',
 '39.CorentinJ/Real-Time-Voice-Cloning',
 '40.swisskyrepo/PayloadsAllTheThings',
 '41.willmcgugan/rich',
 '42.iperov/DeepFaceLab',
 '43.satwikkansal/wtfpython',
 '44.fxsjy/jieba',
 '45.chubin/cheat.sh',
 '46.sherlock-project/sherlock',
 '47.d2l-ai/d2l-zh',
 '48.gto76/python-cheatsheet',
 '48.scikit-learn/scikit-learn',
 '48.tensorflow/models',
 '49.openai/gym',
 '50.facebookresearch/Detectron',
 '51.geekcomputers/Python',
 '52.donnemartin/interactive-coding-challenges',
 '53.0xAX/linux-insides',
 '54.mitmproxy/mitmproxy',
 '55.apache/airflow',
 '56.ansible/ansible',
 '56.pypa/pipenv',
 '57.psf/black',
 '58.encode/django-rest-framework',
 '59.donnemartin/data-science-ipython-notebooks',
 '59.nvbn/thefuck',
 '60.yunjey/pytorch-tutorial',
 '61.shadowsocks/shadowsocks',
 '61.trailofbits/algo',
 '62.explosion/spaCy',
 '63.matterport/Mask_RCNN',
 '63.python/cpython',
 '64.tornadoweb/tornado',
 '65.eriklindernoren/ML-From-Scratch',
 '66.django/django',
 '66.google/python-fire',
 '67.beurtschipper/Depix',
 '68.keon/algorithms',
 '69.wangzheng0822/algo',
 '70.getredash/redash',
 '71.tqdm/tqdm',
 '72.nicolargo/glances',
 '73.sebastianruder/NLP-progress',
 '74.drduh/macOS-Security-and-Privacy-Guide',
 '74.pallets/flask',
 '75.numpy/numpy',
 '76.celery/celery',
 '77.OWASP/CheatSheetSeries',
 '78.facebookresearch/detectron2',
 '79.microsoft/cascadia-code',
 '80.deezer/spleeter',
 '81.bitcoinbook/bitcoinbook',
 '82.magenta/magenta',
 '83.locustio/locust',
 '84.pytorch/examples',
 '85.jumpserver/jumpserver',
 '86.luong-komorebi/Awesome-Linux-Software',
 '87.PaddlePaddle/Paddle',
 '88.reddit-archive/reddit',
 '89.charlax/professional-programming',
 '90.instillai/TensorFlow-Course',
 '91.python-poetry/poetry',
 '92.open-mmlab/mmdetection',
 '93.toml-lang/toml',
 '94.home-assistant/core',
 '94.junyanz/pytorch-CycleGAN-and-pix2pix',
 '94.keras-team/keras',
 '95.bokeh/bokeh',
 '96.httpie/httpie',
 '96.sanic-org/sanic',
 '97.binux/pyspider',
 '98.nginx-proxy/nginx-proxy',
 '99.cookiecutter/cookiecutter'}

In [ ]:
from safetensors.torch import load_file
import polars as pl
from pathlib import Path
import pandas as pd
# defaultdict
from collections import defaultdict
import torch




schema = [('layer', pl.Int8), ('expert', pl.Int8)]
for _, row in py_df.iterrows():
    repo = row["username/repo_name"]
    schema.append((f'{repo}.w1', pl.Float16))
    schema.append((f'{repo}.w3', pl.Float16))

df = pl.DataFrame(schema=schema)

for layer in range(32):
    layer_path = Path(f'output/py/layer={layer:02d}')
    for expert in range(8):
        repos_to_activations = {}
        expert_path = layer_path / f'expert={expert}'

        w1_path = expert_path / 'w=1.safetensors'
        w3_path = expert_path / 'w=3.safetensors'

        w1 = load_file(w1_path)
        w3 = load_file(w3_path)

        assert set(w1.keys()) == all_safetensor_keys, f"Repo missing in w=1 for expert {expert}"
        assert set(w3.keys()) == all_safetensor_keys, f"Repo missing in w=3 for expert {expert}"

        for _, row in py_df.iterrows():
            key = f'{row["rank"]}.{row["username/repo_name"]}'

            w1_activation = w1[key].cpu().to(torch.float16).numpy()
            assert w1_activation.shape == (14336,), f"Unexpected shape for {key} in w=1: {w1_activation.shape}"
            repos_to_activations[f'{row["username/repo_name"]}.w1'] = w1_activation


            w3_activation = w3[key].cpu().to(torch.float16).numpy()
            assert w3_activation.shape == (14336,), f"Unexpected shape for {key} in w=3: {w3_activation.shape}"
            repos_to_activations[f'{row["username/repo_name"]}.w3'] = w3_activation
        
        curr_expert_df = pl.DataFrame(repos_to_activations)
        curr_expert_df = curr_expert_df.with_columns(pl.lit(layer, dtype=pl.Int8).alias("layer"), pl.lit(expert, dtype=pl.Int8).alias("expert"))
        curr_expert_df = curr_expert_df.select(pl.col(df.columns))


    df = pl.concat([df, curr_expert_df], how="vertical")

In [118]:
df

shape: (114_688, 206)
┌───────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ layer ┆ expert ┆ public-api ┆ public-api ┆ … ┆ cookiecutt ┆ cookiecutt ┆ chubin/wtt ┆ chubin/wtt │
│ ---   ┆ ---    ┆ s/public-a ┆ s/public-a ┆   ┆ er/cookiec ┆ er/cookiec ┆ r.in.w1    ┆ r.in.w3    │
│ i8    ┆ i8     ┆ pis.w1     ┆ pis.w3     ┆   ┆ utter.w1   ┆ utter.w3   ┆ ---        ┆ ---        │
│       ┆        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ f16        ┆ f16        │
│       ┆        ┆ f16        ┆ f16        ┆   ┆ f16        ┆ f16        ┆            ┆            │
╞═══════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 7     ┆ 0      ┆ 0.3359375  ┆ 0.212891   ┆ … ┆ -0.443359  ┆ 0.703125   ┆ -0.149414  ┆ -0.294922  │
│ 7     ┆ 0      ┆ -0.478516  ┆ 0.191406   ┆ … ┆ 0.447266   ┆ -0.316406  ┆ -0.157227  ┆ -0.476562  │
│ 7     ┆ 0      ┆ -1.210938  ┆ -0.018921  ┆ … ┆ -0.515625  ┆ 0.012695   ┆ 0.178711   ┆ 0.011414   │
│ 7     ┆ 0      ┆ -0.5625    ┆ -0.482422  ┆ … ┆ -0.212891  ┆ -0.021973  ┆ -0.113281  ┆ 0.714844   │
│ 7     ┆ 0      ┆ 0.22168    ┆ 0.628906   ┆ … ┆ -0.177734  ┆ 0.013306   ┆ -0.328125  ┆ 0.098145   │
│ …     ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 7     ┆ 7      ┆ -0.542969  ┆ 0.527344   ┆ … ┆ 0.178711   ┆ -0.601562  ┆ -0.00264   ┆ 0.519531   │
│ 7     ┆ 7      ┆ -0.038086  ┆ 0.449219   ┆ … ┆ 0.1796875  ┆ 0.597656   ┆ -0.294922  ┆ 0.482422   │
│ 7     ┆ 7      ┆ -0.933594  ┆ -0.007416  ┆ … ┆ 0.314453   ┆ -0.470703  ┆ 1.109375   ┆ -0.498047  │
│ 7     ┆ 7      ┆ -0.15625   ┆ -0.472656  ┆ … ┆ -0.100586  ┆ -0.195312  ┆ 0.032471   ┆ -0.466797  │
│ 7     ┆ 7      ┆ -0.570312  ┆ 0.074707   ┆ … ┆ 0.03833    ┆ -0.349609  ┆ 0.104004   ┆ -0.326172  │
└───────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [99]:
schema = [(row["username/repo_name"], pl.List(pl.Float16)) for _, row in py_df.iterrows()]
df = pl.DataFrame(schema=schema)

shape: (0, 102)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ public-ap ┆ donnemart ┆ TheAlgori ┆ jackfrued ┆ … ┆ binux/pys ┆ nginx-pro ┆ cookiecut ┆ chubin/w │
│ is/public ┆ in/system ┆ thms/Pyth ┆ /Python-1 ┆   ┆ pider     ┆ xy/nginx- ┆ ter/cooki ┆ ttr.in   │
│ -apis     ┆ -design-p ┆ on        ┆ 00-Days   ┆   ┆ ---       ┆ proxy     ┆ ecutter   ┆ ---      │
│ ---       ┆ rim…      ┆ ---       ┆ ---       ┆   ┆ list[f16] ┆ ---       ┆ ---       ┆ list[f16 │
│ list[f16] ┆ ---       ┆ list[f16] ┆ list[f16] ┆   ┆           ┆ list[f16] ┆ list[f16] ┆ ]        │
│           ┆ list[f16] ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘