In [1]:
import pandas as pd

with open('common_words.txt', 'r') as f:
    lines = f.readlines()
common_words = [line.strip() for line in lines if not line.startswith('#')][:1000]


py_df = pd.DataFrame({'rank': range(len(common_words)), 'username/repo_name': common_words})

all_safetensor_keys = set(f'{row["rank"]}.{row["username/repo_name"]}' for _, row in py_df.iterrows())
all_safetensor_keys

FileNotFoundError: [Errno 2] No such file or directory: 'common_words.txt'

In [ ]:
from safetensors.torch import load_file
import polars as pl
from pathlib import Path
import torch


schema = [('expert', pl.Int8)]
for _, row in py_df.iterrows():
    repo = row["username/repo_name"]
    # schema.append((f'{repo}.w1', pl.Float16))
    schema.append((f'{repo}.w3', pl.Float16))


layer_to_df: dict[int, pl.DataFrame] = {}

for layer in range(32):

    df = pl.DataFrame(schema=schema)
    layer_path = Path(f'output/common_words_1k/layer={layer:02d}')

    for expert in range(8):
        repos_to_activations = {}
        expert_path = layer_path / f'expert={expert}'

        w1_path = expert_path / 'w=1.safetensors'
        w3_path = expert_path / 'w=3.safetensors'

        w1 = load_file(w1_path)
        w3 = load_file(w3_path)

        assert set(w1.keys()) == all_safetensor_keys, f"Repo missing in w=1 for expert {expert}"
        assert set(w3.keys()) == all_safetensor_keys, f"Repo missing in w=3 for expert {expert}"

        for _, row in py_df.iterrows():
            key = f'{row["rank"]}.{row["username/repo_name"]}'

            w1_activation = w1[key].cpu().to(torch.float16).numpy()
            assert w1_activation.shape == (14336,), f"Unexpected shape for {key} in w=1: {w1_activation.shape}"
            repos_to_activations[f'{row["username/repo_name"]}.w1'] = w1_activation


            w3_activation = w3[key].cpu().to(torch.float16).numpy()
            assert w3_activation.shape == (14336,), f"Unexpected shape for {key} in w=3: {w3_activation.shape}"
            repos_to_activations[f'{row["username/repo_name"]}.w3'] = w3_activation
        
        curr_expert_df = pl.DataFrame(repos_to_activations)
        curr_expert_df = curr_expert_df.with_columns(pl.lit(expert, dtype=pl.Int8).alias("expert"))
        curr_expert_df = curr_expert_df.select(pl.col(df.columns))


        df = pl.concat([df, curr_expert_df], how="vertical")
    
    layer_to_df[layer] = df

DuplicateError: could not create a new DataFrame: column with name 'but.w3' has more than one occurrence

In [ ]:
df = layer_to_df[28]


cols_end_with_w1_suffix = [col for col in df.columns if col.endswith('.w1')]
cols_end_with_w3_suffix = [col for col in df.columns if col.endswith('.w3')]

# df_w1_mean = df.select(*cols_end_with_w1_suffix).mean_horizontal()
df_w3_mean = df.select(*cols_end_with_w3_suffix).mean_horizontal()

# df_w1_mean.arg_sort(descending=True).head(10) // 14336

In [ ]:
df = layer_to_df[28]

df_top_50_indices = df.drop('expert').select(
    pl.all().arg_sort(descending=True).head(10)
)

df_top_50_values = df.drop('expert').select(
    pl.all().sort(descending=True).head(10)
)

df_top_50_values

# df_top_50_indices
df_top_50_indices // 14336

shape: (10, 20)
┌────────┬───────┬───────┬───────┬───┬───────┬────────┬───────┬───────┐
│ The.w3 ┆ Be.w3 ┆ To.w3 ┆ Of.w3 ┆ … ┆ As.w3 ┆ You.w3 ┆ Do.w3 ┆ At.w3 │
│ ---    ┆ ---   ┆ ---   ┆ ---   ┆   ┆ ---   ┆ ---    ┆ ---   ┆ ---   │
│ u32    ┆ u32   ┆ u32   ┆ u32   ┆   ┆ u32   ┆ u32    ┆ u32   ┆ u32   │
╞════════╪═══════╪═══════╪═══════╪═══╪═══════╪════════╪═══════╪═══════╡
│ 5      ┆ 5     ┆ 5     ┆ 5     ┆ … ┆ 5     ┆ 5      ┆ 5     ┆ 5     │
│ 3      ┆ 2     ┆ 3     ┆ 3     ┆ … ┆ 3     ┆ 3      ┆ 3     ┆ 3     │
│ 0      ┆ 6     ┆ 0     ┆ 0     ┆ … ┆ 6     ┆ 2      ┆ 5     ┆ 5     │
│ 6      ┆ 3     ┆ 6     ┆ 5     ┆ … ┆ 5     ┆ 5      ┆ 6     ┆ 2     │
│ 2      ┆ 5     ┆ 7     ┆ 6     ┆ … ┆ 2     ┆ 6      ┆ 6     ┆ 6     │
│ 6      ┆ 7     ┆ 5     ┆ 6     ┆ … ┆ 0     ┆ 0      ┆ 5     ┆ 6     │
│ 1      ┆ 0     ┆ 2     ┆ 2     ┆ … ┆ 2     ┆ 7      ┆ 2     ┆ 0     │
│ 5      ┆ 2     ┆ 2     ┆ 2     ┆ … ┆ 2     ┆ 2      ┆ 6     ┆ 2     │
│ 5      ┆ 1     ┆ 2     ┆ 1     ┆ … ┆ 4     ┆ 0      ┆ 5     ┆ 5     │
│ 6      ┆ 2     ┆ 5     ┆ 0     ┆ … ┆ 6     ┆ 1      ┆ 0     ┆ 2     │
└────────┴───────┴───────┴───────┴───┴───────┴────────┴───────┴───────┘

In [ ]:
fname = 'common_words.txt'

# read all lines not starting with #:
with open(fname, 'r') as f:
    lines = f.readlines()
common_words = [line.strip() for line in lines if not line.startswith('#')]
common_words

['the',
 'of',
 'and',
 'to',
 'a',
 'in',
 'that',
 'I',
 'was',
 'he',
 'his',
 'with',
 'is',
 'it',
 'for',
 'as',
 'had',
 'you',
 'not',
 'be',
 'on',
 'at',
 'by',
 'her',
 'which',
 'have',
 'or',
 'from',
 'this',
 'but',
 'all',
 'him',
 'she',
 'were',
 'they',
 'my',
 'are',
 'so',
 'me',
 'their',
 'an',
 'one',
 'de',
 'we',
 'who',
 'would',
 'said',
 'been',
 'no',
 'He',
 'will',
 'them',
 'when',
 'if',
 'there',
 'more',
 'out',
 'And',
 'It',
 'any',
 'up',
 'into',
 'your',
 'has',
 'do',
 'what',
 'could',
 'but',
 'our',
 'than',
 'other',
 'some',
 'very',
 'man',
 'upon',
 'about',
 'its',
 'only',
 'time',
 'may',
 'la',
 'like',
 'little',
 'then',
 'now',
 'should',
 'can',
 'made',
 'did',
 'such',
 'A',
 'great',
 'In',
 'must',
 'these',
 'two',
 'before',
 'see',
 'us',
 'over',
 'et',
 'much',
 'know',
 'after',
 'she',
 'first',
 'i',
 'good',
 'Mr',
 'down',
 'never',
 'most',
 'You',
 'where',
 'those',
 'old',
 'men',
 'own',
 'shall',
 'le',
 'came',
 'Project',
 'without',
 'come',
 'make',
 'This',
 'being',
 'day',
 'might',
 'long',
 'through',
 'himself',
 'work',
 'how',
 'go',
 'am',
 'If',
 'way',
 'en',
 'even',
 'que',
 'many',
 'well',
 'say',
 'They',
 'it',
 'every',
 'We',
 'too',
 'think',
 'under',
 'life',
 'went',
 'back',
 'same',
 'There',
 'last',
 'found',
 'take',
 'people',
 'thought',
 'here',
 'still',
 'les',
 'just',
 'while',
 'def',
 'also',
 'again',
 'against',
 'place',
 'away',
 'him',
 'get',
 'To',
 'young',
 'die',
 'though',
 'yet',
 'What',
 'give',
 'hand',
 'eyes',
 'ever',
 'Then',
 'part',
 'des',
 'left',
 'When',
 'things',
 'saw',
 'years',
 'took',
 'nothing',
 'put',
 'new',
 'three',
 'always',
 'und',
 'off',
 'As',
 'once',
 'another',
 'His',
 'right',
 "don't",
 'between',
 'each',
 'For',
 'face',
 'because',
 'whom',
 'That',
 'few',
 'der',
 'tell',
 'son',
 'love',
 'far',
 'un',
 'seemed',
 'house',
 'hw',
 'got',
 'God',
 'head',
 'called',
 'looked',
 'At',
 'whole',
 'set',
 'find',
 'Mrs',
 'world',
 'having',
 'thing',
 'both',
 'told',
 'let',
 'look',
 'THE',
 'night',
 'going',
 'heard',
 'mind',
 'knew',
 'No',
 'heart',
 'seen',
 'se',
 'days',
 'qui',
 'name',
 'among',
 'done',
 'better',
 'So',
 'full',
 'something',
 'du',
 'moment',
 'gave',
 'country',
 'er',
 'almost',
 'Gutenberg',
 'soon',
 'them',
 'course',
 'On',
 'cannot',
 'asked',
 'small',
 'ne',
 'enough',
 'il',
 'want',
 'side',
 'woman',
 'however',
 'home',
 'brought',
 'whose',
 'nor',
 'father',
 'me',
 'quite',
 'words',
 'given',
 'till',
 'pos',
 'taken',
 'use',
 'hands',
 'does',
 'OF',
 'until',
 'end',
 'turned',
 'rather',
 'My',
 'thou',
 'best',
 'p',
 'since',
 'felt',
 'word',
 'Lord',
 'used',
 'dans',
 'light',
 'Oh',
 'next',
 'began',
 'less',
 'present',
 'large',
 'water',
 'den',
 'within',
 'door',
 'poor',
 'certain',
 'works',
 'pas',
 'sent',
 'often',
 'tt',
 'stood',
 'power',
 'Now',
 'room',
 'half',
 'public',
 'themselves',
 'morning',
 'Sir',
 'myself',
 'keep',
 'money',
 'mother',
 'her',
 'b',
 'une',
 'By',
 'thy',
 'hundred',
 'ets',
 'je',
 'kind',
 'order',
 'war',
 'means',
 'form',
 'pour',
 'How',
 'round',
 'received',
 'voice',
 'believe',
 'y',
 'white',
 'Miss',
 'anything',
 'near',
 'others',
 'thus',
 'passed',
 'matter',
 "I'm",
 'Well',
 'year',
 'read',
 'true',
 'All',
 'you',
 'point',
 'herself',
 'Of',
 'friend',
 'state',
 'person',
 'wife',
 'already',
 'One',
 'above',
 'high',
 'met',
 'says',
 'together',
 'why',
 'perhaps',
 'death',
 'dear',
 'fact',
 'least',
 'case',
 'hear',
 'With',
 'known',
 'English',
 'four',
 'hope',
 'au',
 'along',
 'leave',
 'sure',
 'children',
 'during',
 'open',
 'Yes',
 'New',
 'several',
 'King',
 'indeed',
 'therefore',
 'number',
 'feet',
 'wish',
 'gone',
 'girl',
 'lay',
 'either',
 'held',
 'whether',
 'letter',
 'ce',
 'help',
 'free',
 'general',
 'vous',
 'second',
 'alone',
 'return',
 'women',
 'nature',
 'times',
 'land',
 'became',
 'become',
 'thousand',
 'body',
 'air',
 'thee',
 'call',
 'sat',
 'speak',
 'United',
 'itself',
 'States',
 'why',
 'hour',
 'John',
 'reason',
 'M',
 'forth',
 'feel',
 'looking',
 'following',
 'rest',
 'terms',
 'business',
 'electronic',
 'behind',
 'making',
 'zu',
 "I'll",
 'cried',
 'answered',
 'plus',
 'really',
 'friends',
 'towards',
 'child',
 'lost',
 'human',
 'replied',
 'kept',
 'coming',
 'five',
 'king',
 'After',
 'different',
 'care',
 'fire',
 'short',
 'manner',
 'mean',
 'city',
 'fell',
 'able',
 'need',
 'These',
 'French',
 'question',
 'family',
 'boy',
 'cause',
 'Her',
 'Do',
 'seems',
 'strong',
 'par',
 'ten',
 'O',
 'England',
 'possible',
 'dead',
 'returned',
 'bring',
 'sur',
 'Foundation',
 'live',
 'around',
 'doubt',
 'From',
 'hard',
 'p',
 'soul',
 'ask',
 'sort',
 'fine',
 'hold',
 'lady',
 'black',
 'beautiful',
 'sense',
 'close',
 'subject',
 'turn',
 'town',
 'followed',
 'law',
 'evening',
 'truth',
 'sa',
 'ground',
 'understand',
 'show',
 'lui',
 'written',
 'n',
 'common',
 'See',
 'est',
 'ought',
 'fear',
 'dark',
 'party',
 'Not',
 'ready',
 'force',
 'carried',
 "can't",
 'early',
 'said',
 'talk',
 'account',
 'answer',
 'ja',
 'paid',
 'across',
 'arms',
 'necessary',
 'si',
 'sometimes',
 'Here',
 'earth',
 'spirit',
 'saying',
 'das',
 'idea',
 'eBook',
 'character',
 'reached',
 'copyright',
 'sea',
 'appeared',
 'van',
 'sight',
 'interest',
 'six',
 'St',
 'General',
 'von',
 'book',
 'seem',
 'taking',
 'ye',
 'continued',
 'avec',
 'spoke',
 'strange',
 'copy',
 'age',
 'meet',
 'longer',
 'story',
 'sn',
 'deep',
 'nearly',
 'line',
 'further',
 'feeling',
 'Footnote',
 'later',
 'suddenly',
 'sir',
 'added',
 'sich',
 'brother',
 'neither',
 'stand',
 "I've",
 'art',
 'real',
 "it's",
 'nicht',
 'toward',
 'rose',
 'es',
 'beyond',
 'again',
 'laws',
 'sie',
 'miles',
 'CHAPTER',
 'everything',
 'pretty',
 'act',
 'suppose',
 'comes',
 'ich',
 'except',
 'table',
 'hours',
 'river',
 'cut',
 'eye',
 'change',
 'Let',
 'past',
 'nous',
 'natural',
 'entered',
 'Some',
 'none',
 'happy',
 "It's",
 'Il',
 'position',
 'France',
 'else',
 'Lady',
 'clear',
 'late',
 'American',
 "didn't",
 'bed',
 'laid',
 'Is',
 'cold',
 'bad',
 'sound',
 'remember',
 'view',
 'life',
 'led',
 'low',
 'time',
 'mit',
 'forward',
 'fair',
 'although',
 'makes',
 'purpose',
 'knowledge',
 'living',
 'pay',
 'receive',
 'blood',
 'comme',
 'army',
 'daughter',
 'note',
 'opened',
 'run',
 'Dr',
 'el',
 'doing',
 'fall',
 'dem',
 'effect',
 'pass',
 'sun',
 'road',
 'ety',
 'avait',
 'ses',
 'husband',
 'charge',
 'tried',
 'certainly',
 'important',
 'Literary',
 'wanted',
 'service',
 'front',
 'red',
 'TO',
 'probably',
 'future',
 'pr',
 'placed',
 'especially',
 'quill',
 'desire',
 'OR',
 'elle',
 'send',
 'office',
 'Archive',
 'London',
 'greater',
 'La',
 'te',
 'big',
 'letters',
 'peace',
 'hair',
 'pleasure',
 'lived',
 'including',
 'fld',
 'horse',
 'glad',
 'remained',
 'opinion',
 'various',
 'het',
 'hath',
 'bien',
 'An',
 'history',
 'play',
 'agreement',
 'died',
 'tout',
 'cd',
 'wrote',
 'wild',
 "an'",
 'ist',
 'ran',
 "'I",
 'government',
 'donations',
 'save',
 'als',
 'length',
 'Ah',
 'master',
 'latter',
 'Yet',
 'persons',
 'col',
 'hardly',
 'gold',
 'paper',
 'particular',
 'mark',
 'Who',
 'information',
 'cette',
 'bear',
 'Thus',
 'fellow',
 'church',
 'attention',
 'according',
 'wind',
 'per',
 'eBooks',
 'company',
 'walked',
 'chief',
 'strength',
 'all',
 'gentleman',
 'mine',
 'Paris',
 'object',
 'us',
 'unless',
 'duty',
 'drew',
 'single',
 'distance',
 'books',
 'deal',
 'mais',
 'visit',
 'man',
 'foot',
 'beauty',
 'beginning',
 'heavy',
 'ein',
 'standing',
 'knows',
 'thinking',
 'loved',
 'carry',
 'immediately',
 'Captain',
 'unto',
 'e',
 'try',
 'De',
 'rich',
 'plain',
 'sweet',
 'Madame',
 'Le',
 'seeing',
 'minutes',
 'follow',
 'trouble',
 'yourself',
 'write',
 'chance',
 'regard',
 'filled',
 'S',
 'trees',
 'ou',
 "won't",
 'presence',
 'merely',
 'auf',
 'YOU',
 'secret',
 'Our',
 'former',
 'mere',
 'appear',
 'struck',
 'learned',
 'arm',
 'giving',
 'happened',
 "man's",
 'influence',
 'SEE',
 'instead',
 'condition',
 'twenty',
 'work',
 'window',
 'George',
 'Where',
 'afraid',
 'below',
 'wrong',
 'months',
 'day',
 'silence',
 'May',
 'broken',
 'raised',
 'u',
 'outside',
 'getting',
 'caught',
 'While',
 'simple',
 'lips',
 'figure',
 'ago',
 'reach',
 'easily',
 'noble',
 'whatever',
 'dit',
 'thoughts',
 'een',
 'ancient',
 'blue',
 'parts',
 'leaving',
 'agree',
 'generally',
 'Your',
 'showed',
 'AND',
 'easy',
 'ship',
 'action',
 'stay',
 'hat',
 'moved',
 'property',
 'fit',
 'enemy',
 'states',
 'way',
 'grew',
 'afterwards',
 'born',
 'places',
 'York',
 'impossible',
 'State',
 'worth',
 'http',
 'arrived',
 'occasion',
 'remain',
 'please',
 'green',
 'married',
 'that',
 'third',
 'mouth',
 'sleep',
 'period',
 'fresh',
 'faith',
 'system',
 'writing',
 'there',
 'boys',
 'horses',
 'entirely',
 'out',
 'smile',
 'blockquote',
 'goes',
 'usual',
 'Charles',
 'covered',
 'appearance',
 'bound',
 'respect',
 'quiet',
 'beside',
 'dinner',
 'expression',
 'stopped',
 'William',
 'slowly',
 'considerable',
 'Prince',
 'somewhat',
 'walk',
 'away',
 'wonder',
 'PROJECT',
 'Mary',
 'greatest',
 'provide',
 'etext',
 'German',
 'perfect',
 'court',
 'exclaimed',
 'youth',
 'Come',
 'cost',
 'etc',
 'scarcely',
 'sudden',
 'Christian',
 'evil',
 'danger',
 'main',
 'battle',
 'wished',
 'command',
 'notice',
 'piece',
 'political',
 'sister',
 'trying',
 'proper',
 'c',
 'started',
 'considered',
 'British',
 'allowed',
 'expected',
 'joy',
 'private',
 'bright',
 'result',
 'Government',
 'Their',
 'school',
 'sit',
 'language',
 ...]

In [ ]:
df_top_50_values

shape: (10, 20)
┌─────────┬─────────┬─────────┬─────────┬───┬─────────┬─────────┬─────────┬─────────┐
│ The.w3  ┆ Be.w3   ┆ To.w3   ┆ Of.w3   ┆ … ┆ As.w3   ┆ You.w3  ┆ Do.w3   ┆ At.w3   │
│ ---     ┆ ---     ┆ ---     ┆ ---     ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ f16     ┆ f16     ┆ f16     ┆ f16     ┆   ┆ f16     ┆ f16     ┆ f16     ┆ f16     │
╞═════════╪═════════╪═════════╪═════════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ 18.75   ┆ 23.375  ┆ 21.25   ┆ 23.875  ┆ … ┆ 22.25   ┆ 20.875  ┆ 21.25   ┆ 21.875  │
│ 13.3125 ┆ 11.0625 ┆ 15.5625 ┆ 16.125  ┆ … ┆ 17.0    ┆ 12.875  ┆ 13.8125 ┆ 16.0    │
│ 10.0    ┆ 10.6875 ┆ 12.125  ┆ 15.625  ┆ … ┆ 12.5    ┆ 11.125  ┆ 11.75   ┆ 11.8125 │
│ 9.625   ┆ 10.25   ┆ 11.0625 ┆ 12.1875 ┆ … ┆ 12.0    ┆ 11.0625 ┆ 10.875  ┆ 11.1875 │
│ 9.3125  ┆ 10.1875 ┆ 10.9375 ┆ 11.375  ┆ … ┆ 11.9375 ┆ 10.75   ┆ 10.8125 ┆ 11.0625 │
│ 9.125   ┆ 9.4375  ┆ 10.3125 ┆ 11.1875 ┆ … ┆ 11.1875 ┆ 10.5    ┆ 10.75   ┆ 10.5    │
│ 8.625   ┆ 9.25    ┆ 10.0    ┆ 10.9375 ┆ … ┆ 11.1875 ┆ 10.3125 ┆ 10.375  ┆ 10.3125 │
│ 8.375   ┆ 9.125   ┆ 9.875   ┆ 10.875  ┆ … ┆ 11.125  ┆ 9.4375  ┆ 9.6875  ┆ 10.3125 │
│ 8.375   ┆ 9.0625  ┆ 9.8125  ┆ 10.8125 ┆ … ┆ 10.6875 ┆ 9.1875  ┆ 9.5     ┆ 10.1875 │
│ 8.375   ┆ 9.0625  ┆ 9.625   ┆ 10.75   ┆ … ┆ 10.375  ┆ 9.1875  ┆ 9.4375  ┆ 9.6875  │
└─────────┴─────────┴─────────┴─────────┴───┴─────────┴─────────┴─────────┴─────────┘

In [ ]:
from pathlib import Path
import re

lines = Path('genesis.txt').read_text().splitlines()

chapter, verse, text = [], [], []
for line in lines:
    # [chapter:verse] text
    match = re.match(r'\[(\d+):(\d+)\] (.+)', line)
    if not match:
        raise ValueError(f"Line does not match expected format: {line}")
    chapter.append(int(match.group(1)))
    verse.append(int(match.group(2)))
    text.append(match.group(3))

df_genesis = pd.DataFrame({'chapter': chapter, 'verse': verse, 'text': text})
df_genesis.to_csv('genesis.csv', index=False)

FileNotFoundError: [Errno 2] No such file or directory: 'genesis.txt'

'So God made the dome and separated the waters that were under the dome from the waters that were above the dome. And it was so.'

In [ ]:
# join to chapter and text
df_genesis = pd.read_csv('data/genesis.csv')
df_genesis_by_chapter = df_genesis.groupby('chapter').apply(lambda g: g.sort_values('verse')['text'].tolist())
df_genesis_by_chapter = df_genesis_by_chapter.apply(lambda verses: '\n'.join(verses))
df_genesis_by_chapter.to_frame(name='text').reset_index()

/tmp/ipykernel_119397/1620948220.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_genesis_by_chapter = df_genesis.groupby('chapter').apply(lambda g: g.sort_values('verse')['text'].tolist())

    chapter                                               text
0         1  In the beginning when God created the heavens ...
1         2  Thus the heavens and the earth were finished, ...
2         3  Now the serpent was more crafty than any other...
3         4  Now the man knew his wife Eve, and she conceiv...
4         5  This is the list of the descendants of Adam. W...
5         6  When people began to multiply on the face of t...
6         7  Then the LORD said to Noah, "Go into the ark, ...
7         8  But God remembered Noah and all the wild anima...
8         9  God blessed Noah and his sons, and said to the...
9        10  These are the descendants of Noah's sons, Shem...
10       11  Now the whole earth had one language and the s...
11       12  Now the LORD said to Abram, "Go from your coun...
12       13  So Abram went up from Egypt, he and his wife, ...
13       14  In the days of King Amraphel of Shinar, King A...
14       15  After these things the word of the LORD came t...
15       16  Now Sarai, Abram's wife, bore him no children....
16       17  When Abram was ninety-nine years old, the LORD...
17       18  The LORD appeared to Abraham by the oaks of Ma...
18       19  The two angels came to Sodom in the evening, a...
19       20  From there Abraham journeyed toward the region...
20       21  The LORD dealt with Sarah as he had said, and ...
21       22  After these things God tested Abraham. He said...
22       23  Sarah lived one hundred twenty-seven years; th...
23       24  Now Abraham was old, well advanced in years; a...
24       25  Abraham took another wife, whose name was Ketu...
25       26  Now there was a famine in the land, besides th...
26       27  When Isaac was old and his eyes were dim so th...
27       28  Then Isaac called Jacob and blessed him, and c...
28       29  Then Jacob went on his journey, and came to th...
29       30  When Rachel saw that she bore Jacob no childre...
30       31  Now Jacob heard that the sons of Laban were sa...
31       32  Jacob went on his way and the angels of God me...
32       33  Now Jacob looked up and saw Esau coming, and f...
33       34  Now Dinah the daughter of Leah, whom she had b...
34       35  God said to Jacob, "Arise, go up to Bethel, an...
35       36  These are the descendants of Esau (that is, Ed...
36       37  Jacob settled in the land where his father had...
37       38  It happened at that time that Judah went down ...
38       39  Now Joseph was taken down to Egypt, and Potiph...
39       40  Some time after this, the cupbearer of the kin...
40       41  After two whole years, Pharaoh dreamed that he...
41       42  When Jacob learned that there was grain in Egy...
42       43  Now the famine was severe in the land.\nAnd wh...
43       44  Then he commanded the steward of his house, "F...
44       45  Then Joseph could no longer control himself be...
45       46  When Israel set out on his journey with all th...
46       47  So Joseph went and told Pharaoh, "My father an...
47       48  After this Joseph was told, "Your father is il...
48       49  Then Jacob called his sons, and said: "Gather ...
49       50  Then Joseph threw himself on his father's face...